# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "kubernetes" {
    config_context = "pndrs-observability"
    config_path    = "~/.kube/config"
    secret_suffix  = "otel-collector-dev"
  }
}
