# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa

provider "kubernetes" {
  config_path    = "~/.kube/config"
  config_context = "pndrs-observability"
}

provider "helm" {
  kubernetes {
    config_path    = "~/.kube/config"
    config_context = "pndrs-observability"
  }
}

terraform {
  required_version = ">=1.4.6"

  required_providers {
    kubectl = {
      source  = "registry.terraform.io/gavinbunney/kubectl"
      version = "= 1.19.0"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "= 2.16.1"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "= 2.33.0"
    }
    kustomization = {
      source  = "kbst/kustomization"
      version = "= 0.9.6"
    }
    grafana = {
      source  = "grafana/grafana"
      version = "= 3.19.0"
    }
  }
}
